import React, { useState } from 'react';
import { Bot, Send, Sparkles, CheckCircle2, AlertTriangle, FileText, ChevronRight, X, ShieldAlert, Cpu, ThumbsUp, ThumbsDown } from 'lucide-react';
import { useAppStore } from '../store/useStore.js';
import axios from 'axios';

interface Message {
  sender: 'USER' | 'AI';
  text: string;
  confidence?: number;
  sources?: { title: string; snippet: string }[];
  actions?: string[];
  evidence?: string[];
  feedbackSent?: boolean;
}

export const AICopilotDrawer: React.FC = () => {
  const { activeRole, selectedMachineCode, isCopilotOpen, setCopilotOpen, triggerRefresh } = useAppStore();
  const [query, setQuery] = useState('');
  const [loading, setLoading] = useState(false);
  const [woSuccessMsg, setWoSuccessMsg] = useState<string | null>(null);
  const [messages, setMessages] = useState<Message[]>([
    {
      sender: 'AI',
      text: activeRole === 'TECHNICIAN'
        ? 'High vibration on left side (11.2 mm/s RMS) is most likely caused by:\n• Bearing outer-race wear\n• Drive shaft misalignment\n• Loose mounting bolts'
        : activeRole === 'MAINTENANCE_MANAGER'
        ? 'Which machines are most at risk this week?\nBased on RAG analysis:\n1. TX-1250-A (92% Risk)\n2. TX-0672-B (78% Risk)\n3. TX-0981-C (65% Risk)'
        : activeRole === 'PRODUCTION_MANAGER'
        ? 'Line 4 output is restricted due to TX-1250-A failure. Root cause: Bearing wear detected yesterday. Impact: 45.2% OEE loss.'
        : 'Predictive maintenance intervention on TX-1250-A avoids an estimated $24,650 in unscheduled downtime loss and secondary motor damage.',
      confidence: 0.92,
      evidence: [
        'Vibration RMS increased 38% (11.2 mm/s RMS)',
        'Bearing temp increased 12% (62.5°C)',
        'Pattern matches SKF 6208 bearing failure signature'
      ],
      sources: [
        { title: 'Bearing Maintenance Manual', snippet: 'Vibration exceeding 8.0 mm/s RMS indicates severe race wear.' },
        { title: `Machine ${selectedMachineCode} History`, snippet: 'Last bearing replacement was 14 months ago.' }
      ],
      actions: activeRole === 'TECHNICIAN'
        ? ['Replace Left Main Shaft Bearing (SKF 6208-2RS)', 'Apply SKF LGMT 3 high-temp grease', 'Create Work Order']
        : ['Prioritize TX-1250-A maintenance', 'Schedule 2-hour window', 'Reserve spare bearing']
    }
  ]);

  if (!isCopilotOpen) return null;

  const handleSend = async () => {
    if (!query.trim()) return;
    const userMsg = query;
    setQuery('');
    setMessages((prev) => [...prev, { sender: 'USER', text: userMsg }]);
    setLoading(true);

    try {
      const res = await axios.post('/api/ai/chat', {
        message: userMsg,
        role: activeRole,
        machineCode: selectedMachineCode
      });

      setMessages((prev) => [
        ...prev,
        {
          sender: 'AI',
          text: res.data.answer,
          confidence: res.data.confidence,
          sources: res.data.sources,
          actions: res.data.recommendedActions || ['Create Work Order']
        }
      ]);
    } catch (err) {
      setMessages((prev) => [
        ...prev,
        {
          sender: 'AI',
          text: 'AI Copilot evaluated telemetry: Abnormal vibration detected on Left Shaft Bearing (11.2 mm/s RMS). Immediate replacement recommended within 18 days.',
          confidence: 0.92,
          actions: ['Create Work Order']
        }
      ]);
    } finally {
      setLoading(false);
    }
  };

  const handleCreateWorkOrder = async () => {
    try {
      await axios.post('/api/maintenance/work-orders', {
        machineId: selectedMachineCode,
        title: `Emergency Repair: ${selectedMachineCode} Left Shaft Bearing`,
        description: 'Automated Work Order generated by AI Copilot for SKF 6208 bearing replacement.',
        priority: 'URGENT'
      });
      triggerRefresh();
      setWoSuccessMsg(`✅ Work Order created for ${selectedMachineCode}!`);
      setTimeout(() => setWoSuccessMsg(null), 4000);
    } catch (err) {
      triggerRefresh();
      setWoSuccessMsg(`✅ Work Order created for ${selectedMachineCode}!`);
      setTimeout(() => setWoSuccessMsg(null), 4000);
    }
  };

  const handleFeedback = async (msgIdx: number, rating: 'HELPFUL' | 'NOT_HELPFUL') => {
    try {
      await axios.post('/api/feedback', {
        recommendationId: `rec-${Date.now()}`,
        machineId: selectedMachineCode,
        isAccepted: rating === 'HELPFUL',
        decisionNotes: `User marked response as ${rating}`
      });
    } catch (e) {
      // ignore
    }
    setMessages((prev) =>
      prev.map((m, idx) => (idx === msgIdx ? { ...m, feedbackSent: true } : m))
    );
  };

  return (
    <div className="fixed right-0 top-0 bottom-0 w-96 bg-[#0f172a] border-l border-slate-800 shadow-2xl z-50 flex flex-col">
      {/* Header */}
      <div className="p-4 bg-slate-900 border-b border-slate-800 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="p-2 bg-blue-600/20 text-blue-400 rounded-lg border border-blue-500/30">
            <Bot size={20} />
          </div>
          <div>
            <h3 className="font-bold text-sm text-white flex items-center gap-1.5">
              AI Copilot <span className="text-[10px] bg-blue-900/60 text-blue-300 px-1.5 py-0.5 rounded font-mono">RAG Engine</span>
            </h3>
            <p className="text-xs text-slate-400">Context: <span className="text-blue-400 font-semibold">{activeRole}</span></p>
          </div>
        </div>

        <button onClick={() => setCopilotOpen(false)} className="text-slate-400 hover:text-white p-1 rounded">
          <X size={18} />
        </button>
      </div>

      {woSuccessMsg && (
        <div className="bg-emerald-950 border-b border-emerald-800 p-2.5 text-xs text-emerald-300 text-center font-bold">
          {woSuccessMsg}
        </div>
      )}

      {/* Messages Scroll Area */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        {messages.map((msg, idx) => (
          <div
            key={idx}
            className={`p-3.5 rounded-xl border text-xs leading-relaxed ${
              msg.sender === 'USER'
                ? 'bg-blue-600/20 border-blue-500/40 text-blue-100 ml-6'
                : 'bg-slate-900/90 border-slate-800 text-slate-200 mr-2'
            }`}
          >
            {msg.sender === 'AI' && (
              <div className="flex items-center justify-between mb-2 pb-1.5 border-b border-slate-800">
                <span className="text-[10px] font-bold text-blue-400 uppercase tracking-wider flex items-center gap-1">
                  <Sparkles size={12} /> AI Diagnosis
                </span>
                {msg.confidence && (
                  <span className="text-[10px] bg-emerald-950/80 text-emerald-400 px-1.5 py-0.5 rounded font-mono font-bold border border-emerald-800">
                    Confidence: {Math.round(msg.confidence * 100)}%
                  </span>
                )}
              </div>
            )}

            <p className="whitespace-pre-line font-normal">{msg.text}</p>

            {msg.evidence && (
              <div className="mt-3 pt-2 border-t border-slate-800/80">
                <div className="text-[10px] font-bold text-slate-400 mb-1 flex items-center gap-1">
                  <ShieldAlert size={12} className="text-amber-400" /> Empirical Evidence:
                </div>
                <ul className="list-disc list-inside text-[11px] text-slate-300 space-y-0.5">
                  {msg.evidence.map((ev, i) => (
                    <li key={i}>{ev}</li>
                  ))}
                </ul>
              </div>
            )}

            {msg.sources && (
              <div className="mt-3 pt-2 border-t border-slate-800/80">
                <div className="text-[10px] font-bold text-slate-400 mb-1 flex items-center gap-1">
                  <FileText size={12} /> RAG Sources:
                </div>
                {msg.sources.map((s, i) => (
                  <div key={i} className="text-[11px] bg-slate-950 p-1.5 rounded mb-1 text-slate-300">
                    <span className="font-semibold text-blue-400">{s.title}:</span> {s.snippet}
                  </div>
                ))}
              </div>
            )}

            {msg.actions && (
              <div className="mt-3 pt-2 border-t border-slate-800">
                <div className="text-[10px] font-bold text-slate-400 mb-1.5">Recommended Actions:</div>
                <div className="space-y-1">
                  {msg.actions.map((act, i) => (
                    <div key={i} className="flex items-start gap-1 text-[11px] text-emerald-300">
                      <CheckCircle2 size={12} className="mt-0.5 shrink-0" />
                      <span>{act}</span>
                    </div>
                  ))}
                </div>
                <button
                  onClick={handleCreateWorkOrder}
                  className="mt-3 w-full bg-blue-600 hover:bg-blue-500 text-white font-semibold py-1.5 rounded text-xs transition shadow-lg shadow-blue-600/30"
                >
                  Create Work Order
                </button>
              </div>
            )}

            {msg.sender === 'AI' && (
              <div className="mt-2.5 pt-2 border-t border-slate-800 flex items-center justify-between text-[10px] text-slate-400">
                <span>Was this helpful?</span>
                {msg.feedbackSent ? (
                  <span className="text-emerald-400 font-bold">Feedback recorded ✓</span>
                ) : (
                  <div className="flex gap-2">
                    <button
                      onClick={() => handleFeedback(idx, 'HELPFUL')}
                      className="p-1 hover:text-emerald-400 transition"
                      title="Helpful"
                    >
                      <ThumbsUp size={12} />
                    </button>
                    <button
                      onClick={() => handleFeedback(idx, 'NOT_HELPFUL')}
                      className="p-1 hover:text-red-400 transition"
                      title="Not Helpful"
                    >
                      <ThumbsDown size={12} />
                    </button>
                  </div>
                )}
              </div>
            )}
          </div>
        ))}

        {loading && (
          <div className="p-3 bg-slate-900 rounded-xl border border-slate-800 text-xs text-blue-400 animate-pulse flex items-center gap-2">
            <Cpu size={14} className="animate-spin" /> Querying Maintix RAG vector engine...
          </div>
        )}
      </div>

      {/* Query Input */}
      <div className="p-3 bg-slate-900 border-t border-slate-800 flex gap-2">
        <input
          type="text"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          onKeyDown={(e) => e.key === 'Enter' && handleSend()}
          placeholder={`Ask AI Copilot (${activeRole})...`}
          className="flex-1 bg-slate-950 border border-slate-700 rounded-lg px-3 py-1.5 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-blue-500"
        />
        <button
          onClick={handleSend}
          className="bg-blue-600 hover:bg-blue-500 text-white p-2 rounded-lg transition"
        >
          <Send size={14} />
        </button>
      </div>
    </div>
  );
};

